<?php
/**
 * LeadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers, messaging and prospect data manipulation.
 *
 * OpenAPI spec version: 1.10.0
 * Contact: it@sirena.app
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LeadTest Class Doc Comment
 *
 * @category    Class
 * @description Lead data. Note that a contact channel (phone or email) or a recorded call **MUST** be provided.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LeadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Lead"
     */
    public function testLead()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {
    }

    /**
     * Test attribute "provider_lead_id"
     */
    public function testPropertyProviderLeadId()
    {
    }

    /**
     * Test attribute "utm_source"
     */
    public function testPropertyUtmSource()
    {
    }

    /**
     * Test attribute "utm_medium"
     */
    public function testPropertyUtmMedium()
    {
    }

    /**
     * Test attribute "utm_campaign"
     */
    public function testPropertyUtmCampaign()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "phones"
     */
    public function testPropertyPhones()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "call_in"
     */
    public function testPropertyCallIn()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "nin"
     */
    public function testPropertyNin()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "sub_locality"
     */
    public function testPropertySubLocality()
    {
    }

    /**
     * Test attribute "locality"
     */
    public function testPropertyLocality()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "zip_code"
     */
    public function testPropertyZipCode()
    {
    }

    /**
     * Test attribute "listing_title"
     */
    public function testPropertyListingTitle()
    {
    }

    /**
     * Test attribute "listing_url"
     */
    public function testPropertyListingUrl()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "store"
     */
    public function testPropertyStore()
    {
    }

    /**
     * Test attribute "agent"
     */
    public function testPropertyAgent()
    {
    }

    /**
     * Test attribute "lead_id"
     */
    public function testPropertyLeadId()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {
    }

    /**
     * Test attribute "campaign"
     */
    public function testPropertyCampaign()
    {
    }

    /**
     * Test attribute "history"
     */
    public function testPropertyHistory()
    {
    }
}
