<?php
/**
 * NewEventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers, messaging and prospect data manipulation.
 *
 * OpenAPI spec version: 1.10.0
 * Contact: it@sirena.app
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NewEventTest Class Doc Comment
 *
 * @category    Class
 * @description NewEvent
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NewEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewEvent"
     */
    public function testNewEvent()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "provider_id"
     */
    public function testPropertyProviderId()
    {
    }

    /**
     * Test attribute "utm_source"
     */
    public function testPropertyUtmSource()
    {
    }

    /**
     * Test attribute "started_at"
     */
    public function testPropertyStartedAt()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "recording_url"
     */
    public function testPropertyRecordingUrl()
    {
    }

    /**
     * Test attribute "replies_to"
     */
    public function testPropertyRepliesTo()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "delivered"
     */
    public function testPropertyDelivered()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "recipient"
     */
    public function testPropertyRecipient()
    {
    }

    /**
     * Test attribute "attachment"
     */
    public function testPropertyAttachment()
    {
    }

    /**
     * Test attribute "channel_interaction"
     */
    public function testPropertyChannelInteraction()
    {
    }

    /**
     * Test attribute "list"
     */
    public function testPropertyList()
    {
    }

    /**
     * Test attribute "buttons"
     */
    public function testPropertyButtons()
    {
    }

    /**
     * Test attribute "product_list"
     */
    public function testPropertyProductList()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }
}
