<?php
/**
 * ProspectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers, messaging and prospect data manipulation.
 *
 * OpenAPI spec version: 1.10.0
 * Contact: it@sirena.app
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProspectTest Class Doc Comment
 *
 * @category    Class
 * @description Prospect
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProspectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Prospect"
     */
    public function testProspect()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "initial_group"
     */
    public function testPropertyInitialGroup()
    {
    }

    /**
     * Test attribute "initial_group_id"
     */
    public function testPropertyInitialGroupId()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "nin"
     */
    public function testPropertyNin()
    {
    }

    /**
     * Test attribute "user_made"
     */
    public function testPropertyUserMade()
    {
    }

    /**
     * Test attribute "archiving_reason"
     */
    public function testPropertyArchivingReason()
    {
    }

    /**
     * Test attribute "phones"
     */
    public function testPropertyPhones()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "additional_data"
     */
    public function testPropertyAdditionalData()
    {
    }

    /**
     * Test attribute "merged"
     */
    public function testPropertyMerged()
    {
    }

    /**
     * Test attribute "absence_message"
     */
    public function testPropertyAbsenceMessage()
    {
    }

    /**
     * Test attribute "leads"
     */
    public function testPropertyLeads()
    {
    }

    /**
     * Test attribute "agent"
     */
    public function testPropertyAgent()
    {
    }

    /**
     * Test attribute "assigned"
     */
    public function testPropertyAssigned()
    {
    }

    /**
     * Test attribute "next_reminder"
     */
    public function testPropertyNextReminder()
    {
    }

    /**
     * Test attribute "first_contacted_at"
     */
    public function testPropertyFirstContactedAt()
    {
    }

    /**
     * Test attribute "sent_working_hour_message"
     */
    public function testPropertySentWorkingHourMessage()
    {
    }

    /**
     * Test attribute "facebook_due_at"
     */
    public function testPropertyFacebookDueAt()
    {
    }

    /**
     * Test attribute "instagram_due_at"
     */
    public function testPropertyInstagramDueAt()
    {
    }

    /**
     * Test attribute "whats_app_due_at"
     */
    public function testPropertyWhatsAppDueAt()
    {
    }
}
