<?php
/**
 * SavingPlanProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers, messaging and prospect data manipulation.
 *
 * OpenAPI spec version: 1.10.0
 * Contact: it@sirena.app
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SavingPlanProductTest Class Doc Comment
 *
 * @category    Class
 * @description SavingPlanProduct
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SavingPlanProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SavingPlanProduct"
     */
    public function testSavingPlanProduct()
    {
    }

    /**
     * Test attribute "good_type"
     */
    public function testPropertyGoodType()
    {
    }

    /**
     * Test attribute "good_sub_type"
     */
    public function testPropertyGoodSubType()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "plan_type"
     */
    public function testPropertyPlanType()
    {
    }

    /**
     * Test attribute "monthly_payments_estimate"
     */
    public function testPropertyMonthlyPaymentsEstimate()
    {
    }

    /**
     * Test attribute "credit_amount_estimate"
     */
    public function testPropertyCreditAmountEstimate()
    {
    }
}
