<?php
/**
 * ProspectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers, messaging and prospect data manipulation.
 *
 * OpenAPI spec version: 1.10.0
 * Contact: it@sirena.app
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProspectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProspectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCSAT
     *
     * .
     *
     */
    public function testCreateCSAT()
    {
    }

    /**
     * Test case for createInteractionByProspectId
     *
     * .
     *
     */
    public function testCreateInteractionByProspectId()
    {
    }

    /**
     * Test case for deleteProspect
     *
     * .
     *
     */
    public function testDeleteProspect()
    {
    }

    /**
     * Test case for deprecatedGetArchivingReasons
     *
     * .
     *
     */
    public function testDeprecatedGetArchivingReasons()
    {
    }

    /**
     * Test case for getContactsSelection
     *
     * .
     *
     */
    public function testGetContactsSelection()
    {
    }

    /**
     * Test case for getInteractionById
     *
     * .
     *
     */
    public function testGetInteractionById()
    {
    }

    /**
     * Test case for getInteractions
     *
     * .
     *
     */
    public function testGetInteractions()
    {
    }

    /**
     * Test case for getProspectAdditionalFieldsById
     *
     * .
     *
     */
    public function testGetProspectAdditionalFieldsById()
    {
    }

    /**
     * Test case for getProspectById
     *
     * .
     *
     */
    public function testGetProspectById()
    {
    }

    /**
     * Test case for getProspectInteractions
     *
     * .
     *
     */
    public function testGetProspectInteractions()
    {
    }

    /**
     * Test case for getProspectQuotes
     *
     * .
     *
     */
    public function testGetProspectQuotes()
    {
    }

    /**
     * Test case for getProspects
     *
     * .
     *
     */
    public function testGetProspects()
    {
    }

    /**
     * Test case for getQuoteById
     *
     * .
     *
     */
    public function testGetQuoteById()
    {
    }

    /**
     * Test case for getQuotes
     *
     * .
     *
     */
    public function testGetQuotes()
    {
    }

    /**
     * Test case for newProspectQuote
     *
     * .
     *
     */
    public function testNewProspectQuote()
    {
    }

    /**
     * Test case for transferProspect
     *
     * .
     *
     */
    public function testTransferProspect()
    {
    }

    /**
     * Test case for updateAdditionalData
     *
     * .
     *
     */
    public function testUpdateAdditionalData()
    {
    }

    /**
     * Test case for updateInteractionById
     *
     * .
     *
     */
    public function testUpdateInteractionById()
    {
    }

    /**
     * Test case for updateProspectById
     *
     * .
     *
     */
    public function testUpdateProspectById()
    {
    }

    /**
     * Test case for updateProspectQuote
     *
     * .
     *
     */
    public function testUpdateProspectQuote()
    {
    }
}
